name: CI

on: 
  push:
    paths:
      - "Plugin/**"
  workflow_dispatch:

jobs:
  run-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          git submodule update --init --recursive;
          vcpkg integrate install

      - name: Build
        run: |
          Remove-Item build -Recurse -Force -ErrorAction:SilentlyContinue -Confirm:$False | Out-Null;
          cmake -B build -S Plugin --preset=build-release-msvc-msvc -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake;
          cmake --build build
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: build/Release
          retention-days: 30
