name: Maintenance

on: [push]

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        exclude: './docs'
        extensions: 'c,cc,cpp,cppm,cxx,h,hpp,hxx,inl,inc,ixx,mxx'
        clangFormatVersion: 16
        inplace: True

    - uses: EndBug/add-and-commit@v9
      with:
        committer_name: clang-format
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'chore: style formatting'
